name: cellpose
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch
  - pytorch-cuda==11.7
  - pip
  - pip:
    - cellpose
    - prefect==2.8.7
    - git+https://github.com/fmi-faim/custom-prefect-result@v0.1.7
    - git+https://github.com/fmi-faim/faim-prefect@v0.2.2
